added gps

diff --git a/BASE_summit/Dockerfile b/BASE_summit/Dockerfile
--- a/BASE_summit/Dockerfile
+++ b/BASE_summit/Dockerfile
@@ -43,8 +43,8 @@ RUN sudo apt-get update && \
 ################################################################################
 
 # This is required for sharing Xauthority
-ENV CATKIN_TOPLEVEL_WS="${workspace}/devel"
 ENV QT_X11_NO_MITSHM=1
+ENV CATKIN_TOPLEVEL_WS="${workspace}/devel"
 
 
 # Switch to the workspace
@@ -58,7 +58,8 @@ RUN sudo apt-get update && \
     sudo apt-get install -y python3-pip ros-${ROS_DISTRO}-tf2-msgs build-essential \
     ros-${ROS_DISTRO}-pcl-ros \
     ros-${ROS_DISTRO}-image-transport-plugins python3-colcon-common-extensions \
-    inetutils-ping libuvc-dev
+    inetutils-ping libuvc-dev libasio-dev  ros-${ROS_DISTRO}-robot-localization \
+    ros-${ROS_DISTRO}-nmea-navsat-driver 
 
 # Add environment and colcon utilities to .bashrc
 RUN /bin/bash -c 'echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc && \
@@ -72,6 +73,7 @@ cd src && \
 git clone -b 4.5.x https://github.com/BehaviorTree/BehaviorTree.CPP.git && \
 git clone https://github.com/icclab/ros2_laser_scan_merger.git && \
 git clone https://github.com/icclab/liquid_pickup.git && \
+git clone https://github.com/icclab/moveit_visual_tools.git -b humble-trajectory-viz && \
 git clone -b humble https://github.com/RobotnikAutomation/robotnik_common.git && \
 git clone -b humble https://github.com/icclab/summit_xl_common && \
 git clone -b humble https://github.com/icclab/icclab_summit_xl && \
@@ -79,6 +81,8 @@ git clone -b humble-devel https://github.com/RobotnikAutomation/robotnik_sensors
 git clone https://github.com/Juancams/ros_astra_camera -b humble && \
 git clone https://github.com/icclab/add-obstacle-costmap-plugin-layer.git && \
 git clone -b humble https://github.com/PickNikRobotics/ros2_robotiq_gripper.git && \
+git clone https://github.com/gokulp01/ros2-ublox-zedf9p.git && \
+git clone https://github.com/Gaurav-Kapoor-07/Zenoh-Perf-Eval.git && \
 git clone -b ros2 https://github.com/tylerjw/serial.git"
 
 # update dependencies
@@ -93,16 +97,20 @@ RUN  sudo apt-get install -y python3-pcl ros-${ROS_DISTRO}-pcl-ros wget vim ros-
 RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && cd colcon_ws && colcon build --symlink-install"
 
 RUN sudo apt-get update && \
-    sudo apt-get install -y python3-pip
-
-# Install Zenoh (install fails because of no systemd in container so we use a workaround)
-RUN echo "deb [trusted=yes] https://download.eclipse.org/zenoh/debian-repo/ /" | sudo tee -a /etc/apt/sources.list > /dev/null && \
-    sudo apt update && sudo bash -c "apt install -y zenoh-bridge-ros2dds=1.0.2 > /dev/null 2>1; echo $?"
+    sudo apt-get install -y python3-pip xvfb
     
 #RUN sudo apt-get update && \
 #    sudo apt-get install -y python3-pip 
 RUN sudo pip install vo-wot==0.18.12
+# Install Zenoh (install fails because of no systemd in container so we use a workaround)
+
+RUN echo "deb [trusted=yes] https://download.eclipse.org/zenoh/debian-repo/ /" | sudo tee -a /etc/apt/sources.list > /dev/null 
+RUN sudo apt update && sudo bash -c "apt install -y zenoh-bridge-ros2dds=1.0.2 > /dev/null 2>1; echo $?"
+#RUN sudo apt update && sudo apt install -y ros-humble-rmw-zenoh-cpp
+#RUN echo "export RMW_IMPLEMENTATION=rmw_zenoh_cpp"
 COPY summit-vo/summit.py /home/ros
 COPY summit-vo/summit-td.json /home/ros
 COPY summit-vo/summit.yaml /home/ros
+COPY summit-vo/minica.pem /home/ros
+
 
